# Generated by Django 3.1.10 on 2021-07-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': False, 'verbose_name': 'Zařízení', 'verbose_name_plural': 'Zařízení'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'managed': False, 'verbose_name': 'pozice', 'verbose_name_plural': 'pozice'},
        ),
    ]
